// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt70Z5TdsiSpdVMsjKHoFCExDdi6Tpfcg',
    appId: '1:23527963672:web:e0c72e1cff25a2f89d576d',
    messagingSenderId: '23527963672',
    projectId: 'album-biblio-91dce',
    authDomain: 'album-biblio-91dce.firebaseapp.com',
    storageBucket: 'album-biblio-91dce.firebasestorage.app',
    measurementId: 'G-YZRG87WTKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWu8simiw_BJ-mtizKquAc8QUhvsD1QZo',
    appId: '1:23527963672:android:040d3254659c62f59d576d',
    messagingSenderId: '23527963672',
    projectId: 'album-biblio-91dce',
    storageBucket: 'album-biblio-91dce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdSFI1BVKl1IwEyOr--8RUVJM5kdQvd88',
    appId: '1:23527963672:ios:35f2a1e6d11b8f719d576d',
    messagingSenderId: '23527963672',
    projectId: 'album-biblio-91dce',
    storageBucket: 'album-biblio-91dce.firebasestorage.app',
    iosBundleId: 'com.example.albumBiblio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdSFI1BVKl1IwEyOr--8RUVJM5kdQvd88',
    appId: '1:23527963672:ios:35f2a1e6d11b8f719d576d',
    messagingSenderId: '23527963672',
    projectId: 'album-biblio-91dce',
    storageBucket: 'album-biblio-91dce.firebasestorage.app',
    iosBundleId: 'com.example.albumBiblio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt70Z5TdsiSpdVMsjKHoFCExDdi6Tpfcg',
    appId: '1:23527963672:web:21e7ce8415ab45579d576d',
    messagingSenderId: '23527963672',
    projectId: 'album-biblio-91dce',
    authDomain: 'album-biblio-91dce.firebaseapp.com',
    storageBucket: 'album-biblio-91dce.firebasestorage.app',
    measurementId: 'G-SNSX0V0MXG',
  );

}